name: svlite

channels : 
    - default
    - conda-forge

dependencies:
  - python=3.10
  - pip=23.3.1
  - numpy=1.26.0
  - scipy=1.12.0
  - pandas=2.1.4
  - scikit-learn=1.4.0
  - pyarrow=15.0.0
  - sphinx=5.0.2
  - sphinx_rtd_theme=1.1.1
  - pytest=7.1.2
  - networkx=3.2.1
  - ipython=8.12.0
  - nibabel=5.2.0
  - nilearn=0.10.2
  - matplotlib=3.8.4
  - pip:
    - ipykernel==6.22.0